# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Data Carpentry for Public Health Professionals
description:      'Teaching the tools to get computers to do cool science'
url:              http://www.datacarpentry.org/semester-biology
baseurl:          /semester-biology
email:            sheldon.g.waugh.civ@mail.mil
feedbackurl:      docs.google.com/forms/d/1y35uJukuZ9MPKQWWqw0Y8R4VOiaOtFJezDY_t_kJfTs/
author:
  name:           'Sheldon Waugh'
  url:            https://twitter.com/waughsh

github:
  repo:           https://github.com/waughsh/semester-biology
  #               Be sure the 'Issues' feature is activated in 'Settings'
